### ISSUE TITLE
Alternative time windows

### ISSUE THREAD

**Issue by Herteby** [mapbox/node-or-tools#21]
We need to be able to set multiple possible time windows for each customer (for example, one customer might be available 8-10 and 18-20, but not 10-18).

Node-or-tools only accepts one time window per node though...

I looked at the original OR-Tools docs too, and it seems to be the same there, so not just a limit of node-or-tools: https://developers.google.com/optimization/routing/tsp/vehicle_routing_time_windows

This seems like it would be a pretty common request, especially when you want to optimize schedules/routes for a whole week. I don't think this would add much to the computational complexity btw, as you're just splitting a range into blocks.

Do you have any suggestions? :)

**Comment by daniel-j-h** [comment]
Yep reasonable use-case! It's possible for sure and shouldn't be too hard to implement. I already opened a ticket with some notes how to implement this here: https://github.com/mapbox/node-or-tools/issues/8. 

I'm closing this ticket as duplicate - let's keep the discussion re. multiple time windows in #8.

I'm happy to walk you through what needs to be done if you want to give it a try. The tl;dr is: we need to parse an array of time windows at each location instead of a single time window at each location. We then need to pass it through and split the time windows into ranges as you already noted.
